paste('实践6(简单图形)')
x=rnorm(200)
hist(x,col = 'light blue')
rug(x)
x <- rnorm(500)
y <- x+rnorm(500)
plot(y~x)
a=lm(y~x)
abline(a,col='red')
print('Hello World!')
paste('x 的最小值= ',min(x))
demo(graphics)