paste('实践9（数据输入输出）')
x=scan();1.5 2.6 3.7 2.1 8.9 12 -1.2 -4
x= c(1.5,2.6,3.7,2.1,8.9,12,-1.2,-4)
w=read.table(file.choose(),header = T)
setwd('C:/Users/hnjyzdc/Desktop/从数据到结论')
(x=rnorm(20))
write(x,'C:/Users/hnjyzdc/Desktop/从数据到结论/test.txt')
y=scan('C:/Users/hnjyzdc/Desktop/从数据到结论/test.txt')
y=iris;y[1:5,];str(y)
write.table(y,'test.txt',row.names=F)
w=read.table('C:/Users/hnjyzdc/Desktop/从数据到结论/test.txt',header=T)
str(w)
write.csv(y,'test.csv')
v=read.csv('C:/Users/hnjyzdc/Desktop/从数据到结论/test.csv')
str(v)
data=read.table('clipboard')
