setwd('C:/Users/hnjyzdc/Desktop/R/从数据到结论')
w=read.table('Dermatology1.txt',header=T);w[,35]=factor(w[,35])
library(adabag)
set.seed(4410)
a=boosting(V35~.,w)
z0=table(w[,35],predict(a,w)$class)
z0;(E0=(sum(z0)-sum(diag(z0)))/sum(z0))
barplot(a$importance,cex.name=.7)

w=read.table('housing.txt',header=T)
library(mboost)
set.seed(44)
b=blackboost(MEDV~.,data=w)
y0=predict(b,w)
(NMSE0=mean((w$MEDV-y0)^2)/mean((w$MEDV-mean(w$MEDV))^2))


w=read.table('Dermatology1.txt',header=T);w[,35]=factor(w[,35])
library(randomForest)
set.seed(101010)
(a=randomForest(V35~.,data=w,importance=T,proximity=T))
(z0=table(w[,35],predict(a,w)))
layout(matrix(c(1,2,3,4,5,6,7,7,7,8,8,8),nr=2,byrow=T))
for(i in 1:8)barplot(t(importance(a))[i,],cex.names = 0.5)

w=read.table('housing.txt',header = T)
w$CHAS=factor(w$CHAS)
set.seed(1011)
A=randomForest(MEDV~.,data = w,importance=T,proximity=T)
y0=predict(A,w)
(NMSE=mean((w$MEDV-y0)^2)/mean((w$MEDV-mean(w$MEDV))^2))

w=read.table('Dermatology1.txt',header=T);w[,35]=factor(w[,35])
library(e1071)
a=svm(V35~.,data=w,kernal='sigmoid')
z0=table(w[,35],predict(a,w))
z0;(E0=(sum(z0)-sum(diag(z0)))/sum(z0))

w=read.table('housing.txt',header = T)
w$CHAS=factor(w$CHAS)
library(rminer)
set.seed(444)
M=fit(MEDV~.,w,model='svm')
y0=predict(M,w)
(NMSE=mean((w$MEDV-y0)^2)/mean((w$MEDV-mean(w$MEDV))^2))

